#!/usr/bin/env python3

import random
import sys

import numpy as np


def generate_input_and_expected_output_data():
    """
    Write out the input and expected output data to disk.
    """

    # Seed the PRNG.
    random.seed(0)

    # Generate and manipulate the list data.
    x = [random.randint(-100, 100) for _ in range(10000)]
    y = [random.randint(-100, 100) for _ in range(10000)]
    x_dot_y = 0
    for i, j in zip(x, y):
        x_dot_y += i * j
    input_data = x + y
    input_data_strings = [str(np.uint32(n)) for n in input_data]
    expected_output_data_string = str(np.uint32(x_dot_y))


    # Output the input and output files.
    with open("input_data.csv", "w") as input_data_file:
        print(", ".join(input_data_strings), file=input_data_file)
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print(expected_output_data_string, file=expected_output_data_file)


def main():
    """
    Entry point.
    """

    # Generate the data.
    generate_input_and_expected_output_data()

    # Exit successfully.
    return 0


if __name__ == "__main__":
    sys.exit(main())
