#!/usr/bin/env python3

import sys

import numpy as np


def main():
    """
    Entry point.
    """

    # Seed the PRNG.
    np.random.seed(0)

    # Input data.
    signed_input_data = np.random.randint(0, np.iinfo(np.uint32).max, 20000)
    for i in range(10000):
        if signed_input_data[i] % 2:
            signed_input_data[i] = 1
        else:
            signed_input_data[i] = 0
    unsigned_input_data = signed_input_data.astype(np.uint32).tolist()
    unsigned_input_data_strings = [str(n) for n in unsigned_input_data]
    with open("input_data.csv", "w") as input_data_file:
        print(", ".join(unsigned_input_data_strings), file=input_data_file)

    # Output data.
    output_size = np.sum(unsigned_input_data[0:10000])
    signed_output_data = np.zeros(output_size)
    i = 0
    for j in range(10000):
        if signed_input_data[j] == 1:
            signed_output_data[i] = signed_input_data[10000 + j]
            i += 1
    unsigned_output_data = signed_output_data.astype(np.uint32).tolist()
    unsigned_output_data_strings = [str(n) for n in unsigned_output_data]
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print(", ".join(unsigned_output_data_strings), file=expected_output_data_file)

    # Exit successfully.
    return 0


if __name__ == "__main__":
    sys.exit(main())
