#!/usr/bin/env python3

import sys


def main():
    """
    Entry point.
    """

    # Input data.
    with open("input_data.csv", "w") as input_data_file:
        print(0, file=input_data_file)

    # Output data.
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print(123456789, file=expected_output_data_file)

if __name__ == "__main__":
    sys.exit(main())
