#!/usr/bin/env python3

import sys

import numpy as np


def main():
    """
    Entry point.
    """

    # See the PRNG.
    np.random.seed(0)

    # Input data.
    signed_input_data = np.random.randint(-500, 1000, 16384)
    unsigned_input_data = signed_input_data.astype(np.uint32).tolist()
    unsigned_input_data_strings = [str(n) for n in unsigned_input_data]
    with open("input_data.csv", "w") as input_data_file:
        print(", ".join(unsigned_input_data_strings), file=input_data_file)

    # Output data.
    signed_output_data = np.sum(signed_input_data) >> 14
    unsigned_output_data = np.uint32(signed_output_data)
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print(unsigned_output_data, file=expected_output_data_file)

    # Exit successfully.
    return 0


if __name__ == "__main__":
    sys.exit(main())
