#!/usr/bin/env python3

import sys


def main():
    """
    Entry point.
    """

    # Input data.
    with open("input_data.csv", "w") as input_data_file:
        print(0, file=input_data_file)

    # Scratchpad data.
    with open("scratchpad_data.csv", "w") as scratchpad_data_file:
        scratchpad_data_strings = [str(n) for n in range(512)]
        print(", ".join(scratchpad_data_strings), file=scratchpad_data_file)

    # Expected output data.
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print(sum(range(512)), file=expected_output_data_file)


if __name__ == "__main__":
    sys.exit(main())
