#   ___ ___  _ __ ___
#  / __/ _ \| '__/ _ \
# | (_| (_) | | |  __/
#  \___\___/|_|  \___|
#

core:
    # Base architecture.
    architecture: integer
    device_word_width: 32
    immediate_width: 32
    mm_instruction_width: 128
    num_instructions: 16
    num_predicates: 8
    num_registers: 8

    # Instruction features.
    has_multiplier: true
    has_two_word_product_multiplier: true
    has_scratchpad: false
    num_scratchpad_words: 512

    # Instruction memory microarchitecture.
    latch_based_instruction_memory: false
    ram_based_immediate_storage: false

    # Channels.
    num_input_channels: 4
    num_output_channels: 4
    channel_buffer_depth: 2 # Must be >= 2.
    max_num_input_channels_to_check: 2
    num_tags: 3

    # Pipeline features.
    has_speculative_predicate_unit: true
    has_effective_queue_status: true

    # Debugging and profiling features.
    has_debug_monitor: true
    has_performance_counters: true

#  _       _                                           _
# (_)_ __ | |_ ___ _ __ ___ ___  _ __  _ __   ___  ___| |_
# | | '_ \| __/ _ \ '__/ __/ _ \| '_ \| '_ \ / _ \/ __| __|
# | | | | | ||  __/ | | (_| (_) | | | | | | |  __/ (__| |_
# |_|_| |_|\__\___|_|  \___\___/|_| |_|_| |_|\___|\___|\__|
#

interconnect:
    # Router configuration
    router_type: switch
    num_router_sources: 4
    num_router_destinations: 4
    num_input_channels: 4
    num_output_channels: 4
    router_buffer_depth: 2 # Must be >= 2.
    num_physical_planes: 2

#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/
#

system:
    # Host bus information.
    host_word_width: 32 # Fixed, for now.

    # Test memory system.
    num_test_data_memory_words: 32786
    test_data_memory_buffer_depth: 4
