#!/usr/bin/env python3

import sys

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
from gi.repository import Gdk, Gtk

from gui.interface_window import StartWindow


def main():
    """
    Entry point.

    :return: exit code
    """

    # Set the CSS style for the entire application.
    css = b"""
    #schematic_pe_grid button {
        background-image: none;
        background-color: #66ccff;
    }

    #schematic_pe_grid button:hover {
        background-image: none;
        background-color: #77ddff;
    }

    #schematic_pe_grid button:active {
        background-image: none;
        background-color: #55bbff;
    }

    #schematic_pe_grid label {
        text-shadow: none;
    }

    #schematic_data_memory_vbox button {
        background-image: none;
        background-color: #ff9999;
    }

    #schematic_data_memory_vbox button:hover {
        background-image: none;
        background-color: #ffaaaa;
    }

    #schematic_data_memory_vbox button:active {
        background-image: none;
        background-color: #ff8888;
    }

    #schematic_data_memory_vbox label {
        text-shadow: none;
    }
    """
    style_provider = Gtk.CssProvider()
    style_provider.load_from_data(css)
    Gtk.StyleContext.add_provider_for_screen(Gdk.Screen.get_default(), style_provider,
                                             Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)

    # Fire up the application.
    start_window = StartWindow()
    start_window.show_all()
    return Gtk.main()


if __name__ == "__main__":
    sys.exit(main())
