#!/usr/bin/env python3

"""
Usage: yaml_to_json [-h] YAML_FILE JSON_FILE

Convert a YAML file (presumably a configuration file) into its JSON equivalent.

Arguments:
    YAML_FILE       YAML input file
    JSON_FILE       JSON output file

Options:
    -h --help       this description
"""

import json
import sys

from docopt import docopt
import yaml


def main(arguments):
    """
    Entry point.

    :param arguments: arguments parsed by docopt
    :return: exit code
    """

    # --- Argument Parsing ---

    # Check usage, and parse the arguments.
    yaml_file_path = arguments["YAML_FILE"]
    try:
        with open(yaml_file_path) as yaml_file:
            yaml_string = yaml_file.read()
    except:
        e = sys.exc_info()[1]
        error_string = f"Unable to open the YAML file {yaml_file_path}: {str(e)}"
        print(error_string, file=sys.stderr)
        return 1
    json_file_path = arguments["JSON_FILE"]
    try:
        json_file = open(json_file_path, "w")
    except:
        e = sys.exc_info()[1]
        error_string = f"Unable to open the output file {json_file_path} for writing: {str(e)}"
        print(error_string, file=sys.stderr)
        return 1

    # --- YAML to JSON Conversion ---

    # Pretty straight forward.
    dictionary = yaml.load(yaml_string)
    json.dump(dictionary, json_file, sort_keys=True, indent=4)
    json_file.close()

    # Exit successfully.
    return 0


if __name__ == "__main__":
    arguments = docopt(__doc__)
    sys.exit(main(arguments))
