#!/usr/bin/env python3

import random
import sys


def generate_input_and_expected_output_data():
    """
    Write out the input and expected output data to disk.
    """

    # Seed the PRNG.
    random.seed(0)

    # Generate and manipulate the list data.
    first_list = sorted([random.randint(0, 10000) for _ in range(4096)])
    second_list = sorted([random.randint(0, 10000) for _ in range(4096)])
    third_list = sorted([random.randint(0, 10000) for _ in range(4096)])
    fourth_list = sorted([random.randint(0, 10000) for _ in range(4096)])
    input_data = first_list + second_list + third_list + fourth_list
    input_data_strings = [str(n) for n in input_data]
    expected_output_data = sorted(first_list + second_list + third_list + fourth_list)
    expected_output_data_strings = [str(n) for n in expected_output_data]


    # Output the input and output files.
    with open("input_data.csv", "w") as input_data_file:
        print("\n".join(input_data_strings), file=input_data_file)
    with open("expected_output_data.csv", "w") as expected_output_data_file:
        print("\n".join(expected_output_data_strings), file=expected_output_data_file)


def main():
    """
    Entry point.
    """

    # Generate the data.
    generate_input_and_expected_output_data()

    # Exit successfully.
    return 0


if __name__ == "__main__":
    sys.exit(main())
